### ISSUE TITLE
AU Patient snippets - Individual Gender Identity extension fixes

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#10]
https://hl7.org/fhir/extensions/5.1.0/StructureDefinition-individual-genderIdentity.html

This is an international extension not AU, therefore fix comment
- AU Base: https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L138

Enhance the extension snippet as it is complex not simple.

Terminology options in the sub-extension `value` needs to align to ValueSet: https://terminology.hl7.org/5.5.0/ValueSet-gender-identity.html

Add this extension to AU Core Patient snippet

**Comment by robstwd** [comment]
Already mostly done - ie already in AU Core Patient snippet and already complex extension.
Added/updated comments
Fixed via b50680955205ce2e82a45275bbb86192db8b9153
