### ISSUE TITLE
AU Patient snippets - Personal Pronouns extension fixes

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#11]
This is an international extension, not AU Base, therefore update comment - https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L148

Add to AU Core Patient snippet as it has MS

**Comment by robstwd** [comment]
Comment updated; already present in AU Core Patient snippet

Fixed via d771052eb1b9cf2521477ac9ad697db3b33e1d0e
