### ISSUE TITLE
AU Base Patient snippet - recordedSexOrGender extension fixes

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#12]
https://hl7.org/fhir/extensions/5.1.0/StructureDefinition-individual-recordedSexOrGender.html

This is an international extension - therefore fix comment https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L170

Update structure to include sub-extension `genderElementQualifier` as boolean

Sub-extension `acquisitionDate` has wrong datatype - should be `valueDateTime`

Update comment "choice of..." to explicitly indicate one must be deleted: https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L202

Figure out a better way to do jurisdiction terminology representation: https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L221-L225

**Comment by robstwd** [comment]
Multiple fixes implemented by a7876c0e680b78ee5cd5d8362015ea77ac305432
