### ISSUE TITLE
AU Patient snippets - add comment above empty placeholder elements

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#13]
Elements like `<identifier/>` need a comment above to remind user to add one of their own

```
  <!-- add one or more identifiers here -->
  <identifier/>
```

Applies to 
- `<identifier/>` 
- `<name/>`
- `<telecom/>`
- `<address/>`

**Comment by robstwd** [comment]
Added comments for all instances of empty placeholder nodes 

Fixed via cec5a3823a90dce263493cbc74c27ea63d567ecd
