### ISSUE TITLE
Patient snippets - improve comment re 'only one of' for choice elements

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#14]
For choice elements like multiple birth or deceased need a better comment to indicate that one must be deleted.

**Comment by robstwd** [comment]
Added comment like 

`delete one of 'deceasedBoolean' or 'deceasedDateTime' - as a choice element only 1 can be present`

Fixed via fa2d5c7f1c803481bda0ae2937e07f8490fb9edc
