### ISSUE TITLE
Patient.maritalStatus element fixes

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#15]
Fix concept options - missing `U`

https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L29

And CodeSystem URI is wrong; should be 

http://terminology.hl7.org/CodeSystem/v3-MaritalStatus

**Comment by robstwd** [comment]
Removed from AU Base Patient snippet;
Added `U` in the code list for the R4 Patient snippet

Fixed via 59b22009f29ee0df733dbd1aee42ac2d018013be
