### ISSUE TITLE
Patient.contact.relationship terminology fixes

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#16]
Patient.contact.relationship terminology is incomplete; see https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/contact-relationship-type-3

vs 

https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L29

**Comment by robstwd** [comment]
2 Patient snippets were updated with their respective corrected terminologies - the core spec Patient and AU Base Patient.

Fixed via 3f677cacfb62637c2c233ac4c7037cb415fce54b
