### ISSUE TITLE
R4 Spec Patient snippet issues

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#17]
1. add comment preceding `meta`
2. add `active` with boolean choice
3. `multipleBirthInteger` - add some placeholder content
4. add `photo` with `attachment` elements (or just a comment above an empty `<photo/>` node pointing to R4 Attachment datatype)
5. `generalPractitioner` - add choices for types `Practitioner`, `PractitionerRole` and `Organization`
6. add `link` as empty node

**Comment by robstwd** [comment]
Fixed via [a7ce62c0dbeee0ea444031af38afcb7fc3c8d679](https://github.com/robstwd/fhir-snippets/commit/a7ce62c0dbeee0ea444031af38afcb7fc3c8d679)
