### ISSUE TITLE
Patient snippets - birthPlace extension - fixes

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#6]
Issues

- comment should point to International extension not AU Base (https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L92)
- remove from AU Core snippet as no longer MS
- update placeholder for country to be `AUS` consistent with comment on spec ("*ISO 3166 3 letter codes can be used in place of a human readable country name.*" - https://hl7.org/fhir/R4/datatypes-definitions.html#Address.country)

**Comment by robstwd** [comment]
Fixed via b11c940437d734240fcc41dd8461a2c86bc0645a
