### ISSUE TITLE
Patient snippets - Australian Indigenous Status is valueCoding not valueCodeableConcept

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#7]
https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-indigenous-status.html

AU Base Patient snippet - https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L113-L120

AU Core Patient snippet - https://github.com/robstwd/fhir-snippets/blob/main/snippets/FHIR-Patient-examples.code-snippets#L350-L357

**Comment by robstwd** [comment]
Fixed via 7e2922f270742ec3702bda21dfb5abfb9286ca9c
