### ISSUE TITLE
AU Base Patient snippet - add veteran status extension  

### ISSUE THREAD

**Issue by robeastwood-agency** [robstwd/fhir-snippets#8]
https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html

as valueCoding

Extension: https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html

Terminology: https://healthterminologies.gov.au/fhir/CodeSystem/australian-veteran-status-1

(AU Core - no MS)

**Comment by robstwd** [comment]
It's already there - closing
